sudo: required
services:
    - docker

before_install:
    - docker build -t sha01/react-test -f ./client/Dockerfile.dev ./client

script:
    - docker run -e CI=true sha01/react-test npm test -- --coverage

after_success:
    - docker build -t sha01/multi-client ./client
    #Log in to the docker CLI
    - echo "$DOCKER_PASSWORD" | docker login -u  "$DOCKER_ID" --password-stdin
    #Take these images and push them to docker hub
    - docker push  sha01/multi-client:latest
